---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pipelines-repo
- name: pivnet-pasw
- name: pivnet-winfs-injector
run:
  path: pipelines-repo/tasks/build-injected-pasw/task.sh
outputs:
- name: pasw-injected
